### PR TITLE
Merge in hamarituc/xz-backdoor

### LINKED ISSUE #1: Suggestion: Use main repo for decompilation of dropped .o file
I have a work-in-progress decomp(aka i booted up Ghidra and imported the .o file) and I suggest using the main repo as a space for the decomp. You don't have to use mine, you can make your own, just suggesting that.

### PR DESCRIPTION
**Pull request by VivIsBee**
kinda half-closes #1

### CODE REVIEW

**Review by Midar — CHANGES_REQUESTED** [review]
One nit, otherwise LGTM.

**Comment by Midar** [comment]
@hamarituc Are you ok with this?

**Comment by AverseABFun** [comment]
> @hamarituc Are you ok with this?

I mean, it's good to double check with the person who made the repo, but 
[image](https://github.com/Midar/xz-backdoor-documentation/issues/1#issuecomment-2029204063)

**Comment by hamarituc** [comment]
> > @hamarituc Are you ok with this?
> 
> I mean, it's good to double check with the person who made the repo, but [image](https://github.com/Midar/xz-backdoor-documentation/issues/1#issuecomment-2029204063)

I am OK with this. But due to lack of time in the last two days I didn't catch up to the current state of the research. So keep in mind there might be more detailed decompile attempts out there. But I will try to update it in my repo during the next days.

**Comment by Midar** [comment]
> > @hamarituc Are you ok with this?
> 
> I mean, it's good to double check with the person who made the repo, but [image](https://github.com/Midar/xz-backdoor-documentation/issues/1#issuecomment-2029204063)

Ah, sorry, lost track :D

**Pull request merged**
